version: 0.2

run-as: Linux-user-name

env:
  shell: shell-tag
  variables:
    DB_USER: "postgres"
    DB_PASSWORD: "post_123"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -u unittest tests/test_services.py

artifacts:
  files:
    - "**/*"
