version: "3.8"
services:
  dark_list:
    container_name: lista_negra_emails
    build:
      context: .
    environment:
      FLASK_APP: ./src/main.py  # Define el archivo principal para Flask
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:3000"
